//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dictionary> dictionary { get; set; }
        public virtual DbSet<dictionarytype> dictionarytype { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<rolemenu> rolemenu { get; set; }
        public virtual DbSet<systemfunction> systemfunction { get; set; }
        public virtual DbSet<systemparameters> systemparameters { get; set; }
        public virtual DbSet<userrole> userrole { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
