//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class role:BaseModel
    {
        public int RoleId { get; set; }
        public string SystemCoding { get; set; }
        public string RoleName { get; set; }
        public int Sorting { get; set; }
        public string CreateUserName { get; set; }
        public string UpdateUserName { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
